### PR TITLE
fix: bug in tanks sample

### PR DESCRIPTION
**Pull request by Markario**
Small bug in the Tanks sample that prevents local player from clearing the ready menu if the network players are already ready.

### CODE REVIEW

**Comment by uweenukr** [comment]
It seems to work as it when I tested it. I build a standalone and ran the editor as host. Joining the standalone as client i tried hitting ready on both the host first and then the client first. In both instances I didnt get stuck anywhere. Did I test it wrong?

**Comment by Markario** [comment]
For me it's when a third player hits the ready button.

**Comment by Markario** [comment]
GameReadyCheck will hide the menus and enable movement because the network players are ready (and I'm guessing that at that point the localPlayer isn't in that list yet, still wrapping my head around this library) and ShowReadyMenu will then negate that change immediately because the local player is not ready.

**Comment by paulpach** [comment]
@Markario thanks for this PR,  looks like you are on to something.
Could you provide step by step instructions on how to reproduce the bug?

**Comment by uweenukr** [comment]
I tried with 3 clients and regardless of the order they start in it seems to work.
image

**Comment by Markario** [comment]
Interesting 🤔 

Previously I was testing on Unity 2019.4.20f1 with mirrorNG 63.5 on Windows 10. Tested again with Unity 2020.2.4f1 and Mirage 66.2.1 on Mac. Same behavior.

- Loaded the tanks sample
- built and ran 2 apps
- hit play in editor, started host mode (in editor), entered name, hit enter
- started client mode in 1st app, entered name, hit enter
- started client mode in 2nd app, entered name, hit enter, menu doesn't go away

With some logging the behavior I see is:

StartPanel is hidden before the 3rd player has clicked ready
https://github.com/MirageNet/Mirage/blob/8efe7cea0eb8536335f46bf412a8ba71be74ae96/Assets/Mirage/Samples~/Tanks/Scripts/TankGameManager.cs#L123

Then shown again because they are not ready
https://github.com/MirageNet/Mirage/blob/8efe7cea0eb8536335f46bf412a8ba71be74ae96/Assets/Mirage/Samples~/Tanks/Scripts/TankGameManager.cs#L60

After hitting ready, the menu is not hidden because GameReadyCheck() will not be called again (skipped when IsGameReady=true)
https://github.com/MirageNet/Mirage/blob/8efe7cea0eb8536335f46bf412a8ba71be74ae96/Assets/Mirage/Samples~/Tanks/Scripts/TankGameManager.cs#L66

Perhaps it is the case that TankGameManager logic is correct, but instead there is an error in which SpawnedObjects are added to `players` which is checked in https://github.com/MirageNet/Mirage/blob/8efe7cea0eb8536335f46bf412a8ba71be74ae96/Assets/Mirage/Samples~/Tanks/Scripts/TankGameManager.cs#L101

I'm still poking around this library so I have no idea about timing of server<->client syncing in NetworkManager.ClientObjectManager.SpawnedObjects but it seems that the local player's Tank is not in the resulting `players` list and that is why I made the change in this PR.

**Comment by Markario** [comment]
Looking at this again, maybe it's not the intention to allow the order of events I was testing with. Just what felt natural to me, but it appears to work smoothly if I start host mode and both client modes before clicking ready on any of them.

**Comment by uweenukr** [comment]
Ooo a late join scenario. I can see how it would break now. If this was a real game it would make more sense to either block new connections after the game starts or put them in some kind of queue. Since it's a developer example I don't think late joiners are an issue. So I'm ok with the change.

**Comment by Markario** [comment]
Yeah, I wasn't really sure how the sample was intended to be used, but it makes sense that this behavior would be explicitly handled in a real implementation so patching it or not is fine with me. I was testing the sample in the way I eventually intend to implement it myself so I was a bit tunnel visioned.

**Comment by uweenukr** [comment]
I will leave it up to you. If you want to resolve the conflict on the commit so it passes we can merge it. Otherwise if you want to close it that's fine too .

**Pull request merged**
