### PR TITLE
feat: server no longer depends on Unity

### PR DESCRIPTION
**Pull request by phodoval**
BREAKING CHANGE: Authenticators get a `Server` reference in `ServerSetup` instead of `NetworkServer`

**TODO**
- [ ] Switch ILogger for one that doesn't depend on UnityEngine (waiting for uwee to port it from standalone)
- [ ] Test in my project

### CODE REVIEW

**Comment by dragonslaya84** [comment]
Few things.

1) Let's separate everything not part of server change code make things in smaller matches. The Ibehaviour and INetworkBehaviour let's keep out for now dont see it used anywhere.

2) INetworkServer its used on the mono class still. Is that intentional until rest of the files are changing. Should it not be part of Server class instead?

**Comment by phodoval** [comment]
> Few things.
> 
> 1. Let's separate everything not part of server change code make things in smaller matches. The Ibehaviour and INetworkBehaviour let's keep out for now dont see it used anywhere.
> 2. INetworkServer its used on the mono class still. Is that intentional until rest of the files are changing. Should it not be part of Server class instead?

1. Sure, can remove it for now.
2. I kept it on Mono until we have all the classes as standalone, because NetworkIdentity and others depend on INetworkServer directly, and I don't want to break APIs (passing in the pure Server would break API).

**Comment by dragonslaya84** [comment]
Let's try to fix the code smells and bugs so sonar passes.

**Comment by phodoval** [comment]
> Let's try to fix the code smells and bugs so sonar passes.

I've done more work on this, will continue and push it tomorrow.

**Pull request closed without merging**
