### PR TITLE
feat: allow us to add serverid and change it on network identity

### PR DESCRIPTION
**Pull request by dragonslaya84**
This pr let's us add a server id to network identity. Had to make some changes to network world to accommodate new id so that it merges both netid and serverid into one unique id. 

This allows end user's more so for standalone mirage but can also be done in unity to make a master server and have 2-3 of same maps running and pass info to each other based on same serverid.

I have a working code in branch uwee / lymdun working on for an mmo backbones. It requires some modifications still to mirage for it to allow this new feature to work. I may make another pr to add the modification but I think there might be a better way then way I did in that code project.

### CODE REVIEW

**Comment by James-Frowen** [comment]
Adding a byte to every message seems like a lot for a feature most people wont use.

Might be better to allow multiple worlds instead

**Comment by dragonslaya84** [comment]
> Adding a byte to every message seems like a lot for a feature most people wont use.
> 
> Might be better to allow multiple worlds instead

Multiple worlds won't solve anything. Its a single byte. We add a lot of features 90% of mirage user's don't even use. So I don't think that should matter.

**Comment by James-Frowen** [comment]
> Multiple worlds won't solve anything.

You didn't explain how this PR solve anything either.

Can you explain the problem you are trying to solve. Looking at the PR code alone I can think of better ways to do the same thing.

**Comment by James-Frowen** [comment]
Reading the code again. Adding another id for objects seem unnecessary:

The point of netid is to identify an object, adding a second id would now mean you just have 2 ids to identify 1 object. Which just at the surface level sounds super weird.

Another way of looking at this is changing the Id from a 32 bit int, to a 40 bit int. and changing the packed size from 8 bits, to 16 bits. Looking at it from this angle makes it seem un-needed to increase the size because 32 bits is already 4 billion objects.

An alternative could be to add a way to set netid and have the first few bits of it represent server id when needed (maybe with extension methods to get server-id part easier).

**Comment by dragonslaya84** [comment]
> Reading the code again. Adding another id for objects seem unnecessary:
> 
> The point of netid is to identify an object, adding a second id would now mean you just have 2 ids to identify 1 object. Which just at the surface level sounds super weird.
> 
> Another way of looking at this is changing the Id from a 32 bit int, to a 40 bit int. and changing the packed size from 8 bits, to 16 bits. Looking at it from this angle makes it seem un-needed to increase the size because 32 bits is already 4 billion objects.
> 
> An alternative could be to add a way to set netid and have the first few bits of it represent server id when needed (maybe with extension methods to get server-id part easier).

I did say what it solves. It allows sharding. As I mentioned in the pr. Currently netid has collision when you try to spin up the same map and want those maps to sync together through a master server. Spawning 1 player on shard 1 will have the same id of spawning player 2 on shard 2. The netid's cant be synced between server's

If you 

> > Multiple worlds won't solve anything.
> 
> You didn't explain how this PR solve anything either.
> 
> Can you explain the problem you are trying to solve. Looking at the PR code alone I can think of better ways to do the same thing.

**Comment by dragonslaya84** [comment]
> > Multiple worlds won't solve anything.
> 
> You didn't explain how this PR solve anything either.
> 
> Can you explain the problem you are trying to solve. Looking at the PR code alone I can think of better ways to do the same thing.

I did explain what I was solving. Current mirage cannot pass info between 2 of the same server's. Each server spins up netid on there own. Adding this id allows to know which server the netid is from.

**Comment by dragonslaya84** [comment]
> Reading the code again. Adding another id for objects seem unnecessary:
> 
> The point of netid is to identify an object, adding a second id would now mean you just have 2 ids to identify 1 object. Which just at the surface level sounds super weird.
> 
> Another way of looking at this is changing the Id from a 32 bit int, to a 40 bit int. and changing the packed size from 8 bits, to 16 bits. Looking at it from this angle makes it seem un-needed to increase the size because 32 bits is already 4 billion objects.
> 
> An alternative could be to add a way to set netid and have the first few bits of it represent server id when needed (maybe with extension methods to get server-id part easier).

On your last comment line, I think that would be great to do. I just did not want to make changes to netid, that would be a huge breaking change for end user's. I tried to simplify and make the change at least breaking to end user's. While this adds an extra 8 bit to default user's it does not effect end user's when it gets merged. If we go route of packing netid and serverid into a 32bit I figured that was a huge breaking change and would of been alot worse to try get approved then this.

**Comment by James-Frowen** [comment]
I think we can allow netid to be set or generated it a different way, and just default to the current way. Kinda like how you are generating the server id here. I think this would be non-breaking.

**Comment by James-Frowen** [comment]
Maybe an interface like `INetIdGenerator` and then if that field is null we assign a default generator that just increments an id

**Comment by dragonslaya84** [comment]
> Maybe an interface like `INetIdGenerator` and then if that field is null we assign a default generator that just increments an id
> 
> and then you could create a alternative generator to handle serverid stuff too

Will look into this, this weekend and make another branch try test and get working then.

**Pull request closed without merging**
